# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: robosub.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'robosub.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rrobosub.proto\"\x1f\n\x06Header\x12\x15\n\x03src\x18\x01 \x01(\x0e\x32\x08.BoardId\"\x96\x01\n\x0cMotorCommand\x12\x0f\n\x07motor_1\x18\x02 \x01(\x02\x12\x0f\n\x07motor_2\x18\x03 \x01(\x02\x12\x0f\n\x07motor_3\x18\x04 \x01(\x02\x12\x0f\n\x07motor_4\x18\x05 \x01(\x02\x12\x0f\n\x07motor_5\x18\x06 \x01(\x02\x12\x0f\n\x07motor_6\x18\x07 \x01(\x02\x12\x0f\n\x07motor_7\x18\x08 \x01(\x02\x12\x0f\n\x07motor_8\x18\t \x01(\x02\"8\n\x15IndicatorLightCommand\x12\t\n\x01r\x18\x02 \x01(\x02\x12\t\n\x01g\x18\x03 \x01(\x02\x12\t\n\x01\x62\x18\x04 \x01(\x02\"6\n\x0bPrestoState\x12\x0e\n\x06\x65_stop\x18\x02 \x01(\x08\x12\x17\n\x0f\x61utonomy_switch\x18\x03 \x01(\x08\"I\n\x0cSensorBState\x12\x11\n\tvoltage_v\x18\x02 \x01(\x02\x12\x11\n\tcurrent_a\x18\x03 \x01(\x02\x12\x13\n\x0bpressure_pa\x18\x04 \x01(\x02\"\x1c\n\tDebugInfo\x12\x0f\n\x07message\x18\x02 \x01(\t\"\xf3\x01\n\x08\x45nvelope\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12\"\n\tmotor_cmd\x18\n \x01(\x0b\x32\r.MotorCommandH\x00\x12/\n\rindicator_cmd\x18\x0b \x01(\x0b\x32\x16.IndicatorLightCommandH\x00\x12$\n\x0cpresto_state\x18\x0c \x01(\x0b\x32\x0c.PrestoStateH\x00\x12&\n\rsensorb_state\x18\r \x01(\x0b\x32\r.SensorBStateH\x00\x12 \n\ndebug_info\x18\x0e \x01(\x0b\x32\n.DebugInfoH\x00\x42\t\n\x07payload*^\n\x07\x42oardId\x12\x14\n\x10\x42OARD_UNKNOWN_ID\x10\x00\x12\x13\n\x0f\x42OARD_JETSON_ID\x10\x01\x12\x13\n\x0f\x42OARD_PRESTO_ID\x10\x02\x12\x13\n\x0f\x42OARD_SENSOR_ID\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robosub_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOARDID']._serialized_start=668
  _globals['_BOARDID']._serialized_end=762
  _globals['_HEADER']._serialized_start=17
  _globals['_HEADER']._serialized_end=48
  _globals['_MOTORCOMMAND']._serialized_start=51
  _globals['_MOTORCOMMAND']._serialized_end=201
  _globals['_INDICATORLIGHTCOMMAND']._serialized_start=203
  _globals['_INDICATORLIGHTCOMMAND']._serialized_end=259
  _globals['_PRESTOSTATE']._serialized_start=261
  _globals['_PRESTOSTATE']._serialized_end=315
  _globals['_SENSORBSTATE']._serialized_start=317
  _globals['_SENSORBSTATE']._serialized_end=390
  _globals['_DEBUGINFO']._serialized_start=392
  _globals['_DEBUGINFO']._serialized_end=420
  _globals['_ENVELOPE']._serialized_start=423
  _globals['_ENVELOPE']._serialized_end=666
# @@protoc_insertion_point(module_scope)
