// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// led_mux //
// ------- //

#define led_mux_wrap_target 0
#define led_mux_wrap 1
#define led_mux_pio_version 0

static const uint16_t led_mux_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0x6004, //  1: out    pins, 4
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program led_mux_program = {
    .instructions = led_mux_program_instructions,
    .length = 2,
    .origin = -1,
    .pio_version = led_mux_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config led_mux_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + led_mux_wrap_target, offset + led_mux_wrap);
    return c;
}
#endif

