# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robosub.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rrobosub.proto\"\x1f\n\x06Header\x12\x15\n\x03src\x18\x01 \x01(\x0e\x32\x08.BoardId\"\xaf\x01\n\x0cMotorCommand\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12\x0f\n\x07motor_1\x18\x02 \x01(\x02\x12\x0f\n\x07motor_2\x18\x03 \x01(\x02\x12\x0f\n\x07motor_3\x18\x04 \x01(\x02\x12\x0f\n\x07motor_4\x18\x05 \x01(\x02\x12\x0f\n\x07motor_5\x18\x06 \x01(\x02\x12\x0f\n\x07motor_6\x18\x07 \x01(\x02\x12\x0f\n\x07motor_7\x18\x08 \x01(\x02\x12\x0f\n\x07motor_8\x18\t \x01(\x02\"Q\n\x15IndicatorLightCommand\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12\t\n\x01r\x18\x02 \x01(\x02\x12\t\n\x01g\x18\x03 \x01(\x02\x12\t\n\x01\x62\x18\x04 \x01(\x02\"O\n\x0bPrestoState\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12\x0e\n\x06\x65_stop\x18\x02 \x01(\x08\x12\x17\n\x0f\x61utonomy_switch\x18\x03 \x01(\x08\"b\n\x0cSensorBState\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12\x11\n\tvoltage_v\x18\x02 \x01(\x02\x12\x11\n\tcurrent_a\x18\x03 \x01(\x02\x12\x13\n\x0bpressure_pa\x18\x04 \x01(\x02\"5\n\tDebugInfo\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12\x0f\n\x07message\x18\x02 \x01(\t\"\xf3\x01\n\x08\x45nvelope\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12\"\n\tmotor_cmd\x18\n \x01(\x0b\x32\r.MotorCommandH\x00\x12/\n\rindicator_cmd\x18\x0b \x01(\x0b\x32\x16.IndicatorLightCommandH\x00\x12$\n\x0cpresto_state\x18\x0c \x01(\x0b\x32\x0c.PrestoStateH\x00\x12&\n\rsensorb_state\x18\r \x01(\x0b\x32\r.SensorBStateH\x00\x12 \n\ndebug_info\x18\x0e \x01(\x0b\x32\n.DebugInfoH\x00\x42\t\n\x07payload*^\n\x07\x42oardId\x12\x14\n\x10\x42OARD_UNKNOWN_ID\x10\x00\x12\x13\n\x0f\x42OARD_JETSON_ID\x10\x01\x12\x13\n\x0f\x42OARD_PRESTO_ID\x10\x02\x12\x13\n\x0f\x42OARD_SENSOR_ID\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robosub_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOARDID._serialized_start=793
  _BOARDID._serialized_end=887
  _HEADER._serialized_start=17
  _HEADER._serialized_end=48
  _MOTORCOMMAND._serialized_start=51
  _MOTORCOMMAND._serialized_end=226
  _INDICATORLIGHTCOMMAND._serialized_start=228
  _INDICATORLIGHTCOMMAND._serialized_end=309
  _PRESTOSTATE._serialized_start=311
  _PRESTOSTATE._serialized_end=390
  _SENSORBSTATE._serialized_start=392
  _SENSORBSTATE._serialized_end=490
  _DEBUGINFO._serialized_start=492
  _DEBUGINFO._serialized_end=545
  _ENVELOPE._serialized_start=548
  _ENVELOPE._serialized_end=791
# @@protoc_insertion_point(module_scope)
