/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MESSAGE_PB_H_INCLUDED
#define PB_MESSAGE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _operationStatus {
    bool estop; /* Whether EStop is engaged */
    bool manual; /* whether manual or automatic */
} operationStatus;

typedef struct _positionCommand {
    int32_t roll; /* Use signed int to get some directional control */
    int32_t pitch;
    int32_t yaw;
    int32_t surge; /* Had to google these, but this is forward/backward */
    int32_t sway; /* Laterally */
    int32_t heave; /* Up and down */
} positionCommand;

typedef struct _motorCommand {
    float motor1;
    float motor2;
    float motor3;
    float motor4;
    float motor5;
    float motor6;
    float motor7;
    float motor8;
} motorCommand;

typedef struct _dropperCommand {
    uint32_t dropper;
} dropperCommand;

typedef struct _AccelData {
    float x;
    float y;
    float z;
} AccelData;

typedef struct _sensorData {
    uint32_t id;
    pb_size_t which_data;
    union {
        float temperature;
        AccelData accel;
        float amperage;
    } data;
} sensorData;

typedef struct _MyMessage {
    int32_t id;
    char content[64];
} MyMessage;

typedef struct _Envelope {
    pb_size_t which_payload;
    union {
        operationStatus status;
        positionCommand pos;
        MyMessage debug;
        motorCommand motor_msg;
        sensorData readings;
        dropperCommand dropper;
    } payload;
} Envelope;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define operationStatus_init_default             {0, 0}
#define positionCommand_init_default             {0, 0, 0, 0, 0, 0}
#define motorCommand_init_default                {0, 0, 0, 0, 0, 0, 0, 0}
#define dropperCommand_init_default              {0}
#define AccelData_init_default                   {0, 0, 0}
#define sensorData_init_default                  {0, 0, {0}}
#define MyMessage_init_default                   {0, ""}
#define Envelope_init_default                    {0, {operationStatus_init_default}}
#define operationStatus_init_zero                {0, 0}
#define positionCommand_init_zero                {0, 0, 0, 0, 0, 0}
#define motorCommand_init_zero                   {0, 0, 0, 0, 0, 0, 0, 0}
#define dropperCommand_init_zero                 {0}
#define AccelData_init_zero                      {0, 0, 0}
#define sensorData_init_zero                     {0, 0, {0}}
#define MyMessage_init_zero                      {0, ""}
#define Envelope_init_zero                       {0, {operationStatus_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define operationStatus_estop_tag                1
#define operationStatus_manual_tag               2
#define positionCommand_roll_tag                 1
#define positionCommand_pitch_tag                2
#define positionCommand_yaw_tag                  3
#define positionCommand_surge_tag                4
#define positionCommand_sway_tag                 5
#define positionCommand_heave_tag                6
#define motorCommand_motor1_tag                  1
#define motorCommand_motor2_tag                  2
#define motorCommand_motor3_tag                  3
#define motorCommand_motor4_tag                  4
#define motorCommand_motor5_tag                  5
#define motorCommand_motor6_tag                  6
#define motorCommand_motor7_tag                  7
#define motorCommand_motor8_tag                  8
#define dropperCommand_dropper_tag               1
#define AccelData_x_tag                          1
#define AccelData_y_tag                          2
#define AccelData_z_tag                          3
#define sensorData_id_tag                        1
#define sensorData_temperature_tag               2
#define sensorData_accel_tag                     3
#define sensorData_amperage_tag                  4
#define MyMessage_id_tag                         1
#define MyMessage_content_tag                    2
#define Envelope_status_tag                      1
#define Envelope_pos_tag                         2
#define Envelope_debug_tag                       3
#define Envelope_motor_msg_tag                   4
#define Envelope_readings_tag                    5
#define Envelope_dropper_tag                     6

/* Struct field encoding specification for nanopb */
#define operationStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     estop,             1) \
X(a, STATIC,   SINGULAR, BOOL,     manual,            2)
#define operationStatus_CALLBACK NULL
#define operationStatus_DEFAULT NULL

#define positionCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   roll,              1) \
X(a, STATIC,   SINGULAR, SINT32,   pitch,             2) \
X(a, STATIC,   SINGULAR, SINT32,   yaw,               3) \
X(a, STATIC,   SINGULAR, SINT32,   surge,             4) \
X(a, STATIC,   SINGULAR, SINT32,   sway,              5) \
X(a, STATIC,   SINGULAR, SINT32,   heave,             6)
#define positionCommand_CALLBACK NULL
#define positionCommand_DEFAULT NULL

#define motorCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    motor1,            1) \
X(a, STATIC,   SINGULAR, FLOAT,    motor2,            2) \
X(a, STATIC,   SINGULAR, FLOAT,    motor3,            3) \
X(a, STATIC,   SINGULAR, FLOAT,    motor4,            4) \
X(a, STATIC,   SINGULAR, FLOAT,    motor5,            5) \
X(a, STATIC,   SINGULAR, FLOAT,    motor6,            6) \
X(a, STATIC,   SINGULAR, FLOAT,    motor7,            7) \
X(a, STATIC,   SINGULAR, FLOAT,    motor8,            8)
#define motorCommand_CALLBACK NULL
#define motorCommand_DEFAULT NULL

#define dropperCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dropper,           1)
#define dropperCommand_CALLBACK NULL
#define dropperCommand_DEFAULT NULL

#define AccelData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    z,                 3)
#define AccelData_CALLBACK NULL
#define AccelData_DEFAULT NULL

#define sensorData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   ONEOF,    FLOAT,    (data,temperature,data.temperature),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,accel,data.accel),   3) \
X(a, STATIC,   ONEOF,    FLOAT,    (data,amperage,data.amperage),   4)
#define sensorData_CALLBACK NULL
#define sensorData_DEFAULT NULL
#define sensorData_data_accel_MSGTYPE AccelData

#define MyMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    id,                1) \
X(a, STATIC,   SINGULAR, STRING,   content,           2)
#define MyMessage_CALLBACK NULL
#define MyMessage_DEFAULT NULL

#define Envelope_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,status,payload.status),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,pos,payload.pos),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,debug,payload.debug),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,motor_msg,payload.motor_msg),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,readings,payload.readings),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,dropper,payload.dropper),   6)
#define Envelope_CALLBACK NULL
#define Envelope_DEFAULT NULL
#define Envelope_payload_status_MSGTYPE operationStatus
#define Envelope_payload_pos_MSGTYPE positionCommand
#define Envelope_payload_debug_MSGTYPE MyMessage
#define Envelope_payload_motor_msg_MSGTYPE motorCommand
#define Envelope_payload_readings_MSGTYPE sensorData
#define Envelope_payload_dropper_MSGTYPE dropperCommand

extern const pb_msgdesc_t operationStatus_msg;
extern const pb_msgdesc_t positionCommand_msg;
extern const pb_msgdesc_t motorCommand_msg;
extern const pb_msgdesc_t dropperCommand_msg;
extern const pb_msgdesc_t AccelData_msg;
extern const pb_msgdesc_t sensorData_msg;
extern const pb_msgdesc_t MyMessage_msg;
extern const pb_msgdesc_t Envelope_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define operationStatus_fields &operationStatus_msg
#define positionCommand_fields &positionCommand_msg
#define motorCommand_fields &motorCommand_msg
#define dropperCommand_fields &dropperCommand_msg
#define AccelData_fields &AccelData_msg
#define sensorData_fields &sensorData_msg
#define MyMessage_fields &MyMessage_msg
#define Envelope_fields &Envelope_msg

/* Maximum encoded size of messages (where known) */
#define AccelData_size                           15
#define Envelope_size                            78
#define MESSAGE_PB_H_MAX_SIZE                    Envelope_size
#define MyMessage_size                           76
#define dropperCommand_size                      6
#define motorCommand_size                        40
#define operationStatus_size                     4
#define positionCommand_size                     36
#define sensorData_size                          23

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
