/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MESSAGE_PB_H_INCLUDED
#define PB_MESSAGE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Config {
    bool estop; /*  */
    bool manual; /* whether manual or automatic */
} Config;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Config_init_default                      {0, 0}
#define Config_init_zero                         {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Config_estop_tag                         1
#define Config_manual_tag                        2

/* Struct field encoding specification for nanopb */
#define Config_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     estop,             1) \
X(a, STATIC,   SINGULAR, BOOL,     manual,            2)
#define Config_CALLBACK NULL
#define Config_DEFAULT NULL

extern const pb_msgdesc_t Config_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Config_fields &Config_msg

/* Maximum encoded size of messages (where known) */
#define Config_size                              4
#define MESSAGE_PB_H_MAX_SIZE                    Config_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
