/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MESSAGE_PB_H_INCLUDED
#define PB_MESSAGE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _operationStatus {
    bool estop; /* Whether EStop is engaged */
    bool manual; /* whether manual or automatic */
} operationStatus;

typedef struct _positionCommand {
    int32_t roll; /* Use signed int to get some directional control */
    int32_t pitch;
    int32_t yaw;
    int32_t surge; /* Had to google these, but this is forward/backward */
    int32_t sway; /* Laterally */
    int32_t heave; /* Up and down */
} positionCommand;

typedef struct _MyMessage {
    int32_t id;
    char content[64];
} MyMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define operationStatus_init_default             {0, 0}
#define positionCommand_init_default             {0, 0, 0, 0, 0, 0}
#define MyMessage_init_default                   {0, ""}
#define operationStatus_init_zero                {0, 0}
#define positionCommand_init_zero                {0, 0, 0, 0, 0, 0}
#define MyMessage_init_zero                      {0, ""}

/* Field tags (for use in manual encoding/decoding) */
#define operationStatus_estop_tag                1
#define operationStatus_manual_tag               2
#define positionCommand_roll_tag                 3
#define positionCommand_pitch_tag                4
#define positionCommand_yaw_tag                  5
#define positionCommand_surge_tag                6
#define positionCommand_sway_tag                 7
#define positionCommand_heave_tag                8
#define MyMessage_id_tag                         9
#define MyMessage_content_tag                    10

/* Struct field encoding specification for nanopb */
#define operationStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     estop,             1) \
X(a, STATIC,   SINGULAR, BOOL,     manual,            2)
#define operationStatus_CALLBACK NULL
#define operationStatus_DEFAULT NULL

#define positionCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   roll,              3) \
X(a, STATIC,   SINGULAR, SINT32,   pitch,             4) \
X(a, STATIC,   SINGULAR, SINT32,   yaw,               5) \
X(a, STATIC,   SINGULAR, SINT32,   surge,             6) \
X(a, STATIC,   SINGULAR, SINT32,   sway,              7) \
X(a, STATIC,   SINGULAR, SINT32,   heave,             8)
#define positionCommand_CALLBACK NULL
#define positionCommand_DEFAULT NULL

#define MyMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    id,                9) \
X(a, STATIC,   SINGULAR, STRING,   content,          10)
#define MyMessage_CALLBACK NULL
#define MyMessage_DEFAULT NULL

extern const pb_msgdesc_t operationStatus_msg;
extern const pb_msgdesc_t positionCommand_msg;
extern const pb_msgdesc_t MyMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define operationStatus_fields &operationStatus_msg
#define positionCommand_fields &positionCommand_msg
#define MyMessage_fields &MyMessage_msg

/* Maximum encoded size of messages (where known) */
#define MESSAGE_PB_H_MAX_SIZE                    MyMessage_size
#define MyMessage_size                           76
#define operationStatus_size                     4
#define positionCommand_size                     36

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
