/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "robosub.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Header, Header, AUTO)


PB_BIND(MotorCommand, MotorCommand, AUTO)


PB_BIND(IndicatorLightCommand, IndicatorLightCommand, AUTO)


PB_BIND(PrestoState, PrestoState, AUTO)


PB_BIND(SensorBState, SensorBState, AUTO)


PB_BIND(DebugInfo, DebugInfo, AUTO)


PB_BIND(Envelope, Envelope, AUTO)





