/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ROBOSUB_PB_H_INCLUDED
#define PB_ROBOSUB_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* ---------- Common ---------- */
typedef enum _BoardId {
    BoardId_BOARD_UNKNOWN_ID = 0,
    BoardId_BOARD_JETSON_ID = 1,
    BoardId_BOARD_PRESTO_ID = 2,
    BoardId_BOARD_SENSOR_ID = 3
} BoardId;

/* Struct definitions */
typedef struct _Header {
    BoardId src; /* who sent this */
} Header;

/* ------ Presto ------ */
typedef struct _MotorCommand { /* (Jetson to Presto) */
    float motor_1;
    float motor_2;
    float motor_3;
    float motor_4;
    float motor_5;
    float motor_6;
    float motor_7;
    float motor_8;
} MotorCommand;

typedef struct _IndicatorLightCommand { /* (Jetson to Presto) */
    float r; /* Percent 0.0 to 1.0 */
    float g;
    float b;
} IndicatorLightCommand;

typedef struct _PrestoState {
    bool e_stop;
    bool autonomy_switch;
} PrestoState;

/* ------ Sensor Board ------ */
typedef struct _SensorBState {
    float voltage_v;
    float current_a;
    float pressure_pa;
} SensorBState;

/* ------ Debug Info ------ */
typedef struct _DebugInfo {
    pb_callback_t message;
} DebugInfo;

/* Now that there are multiple possible command types coming in or
multiple sensor types coming out we need this so we can determine which
we are using. */
typedef struct _Envelope {
    bool has_header;
    Header header;
    pb_size_t which_payload;
    union {
        MotorCommand motor_cmd;
        IndicatorLightCommand indicator_cmd;
        PrestoState presto_state;
        SensorBState sensorb_state;
        DebugInfo debug_info;
    } payload;
} Envelope;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _BoardId_MIN BoardId_BOARD_UNKNOWN_ID
#define _BoardId_MAX BoardId_BOARD_SENSOR_ID
#define _BoardId_ARRAYSIZE ((BoardId)(BoardId_BOARD_SENSOR_ID+1))

#define Header_src_ENUMTYPE BoardId








/* Initializer values for message structs */
#define Header_init_default                      {_BoardId_MIN}
#define MotorCommand_init_default                {0, 0, 0, 0, 0, 0, 0, 0}
#define IndicatorLightCommand_init_default       {0, 0, 0}
#define PrestoState_init_default                 {0, 0}
#define SensorBState_init_default                {0, 0, 0}
#define DebugInfo_init_default                   {{{NULL}, NULL}}
#define Envelope_init_default                    {false, Header_init_default, 0, {MotorCommand_init_default}}
#define Header_init_zero                         {_BoardId_MIN}
#define MotorCommand_init_zero                   {0, 0, 0, 0, 0, 0, 0, 0}
#define IndicatorLightCommand_init_zero          {0, 0, 0}
#define PrestoState_init_zero                    {0, 0}
#define SensorBState_init_zero                   {0, 0, 0}
#define DebugInfo_init_zero                      {{{NULL}, NULL}}
#define Envelope_init_zero                       {false, Header_init_zero, 0, {MotorCommand_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define Header_src_tag                           1
#define MotorCommand_motor_1_tag                 2
#define MotorCommand_motor_2_tag                 3
#define MotorCommand_motor_3_tag                 4
#define MotorCommand_motor_4_tag                 5
#define MotorCommand_motor_5_tag                 6
#define MotorCommand_motor_6_tag                 7
#define MotorCommand_motor_7_tag                 8
#define MotorCommand_motor_8_tag                 9
#define IndicatorLightCommand_r_tag              2
#define IndicatorLightCommand_g_tag              3
#define IndicatorLightCommand_b_tag              4
#define PrestoState_e_stop_tag                   2
#define PrestoState_autonomy_switch_tag          3
#define SensorBState_voltage_v_tag               2
#define SensorBState_current_a_tag               3
#define SensorBState_pressure_pa_tag             4
#define DebugInfo_message_tag                    2
#define Envelope_header_tag                      1
#define Envelope_motor_cmd_tag                   10
#define Envelope_indicator_cmd_tag               11
#define Envelope_presto_state_tag                12
#define Envelope_sensorb_state_tag               13
#define Envelope_debug_info_tag                  14

/* Struct field encoding specification for nanopb */
#define Header_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    src,               1)
#define Header_CALLBACK NULL
#define Header_DEFAULT NULL

#define MotorCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    motor_1,           2) \
X(a, STATIC,   SINGULAR, FLOAT,    motor_2,           3) \
X(a, STATIC,   SINGULAR, FLOAT,    motor_3,           4) \
X(a, STATIC,   SINGULAR, FLOAT,    motor_4,           5) \
X(a, STATIC,   SINGULAR, FLOAT,    motor_5,           6) \
X(a, STATIC,   SINGULAR, FLOAT,    motor_6,           7) \
X(a, STATIC,   SINGULAR, FLOAT,    motor_7,           8) \
X(a, STATIC,   SINGULAR, FLOAT,    motor_8,           9)
#define MotorCommand_CALLBACK NULL
#define MotorCommand_DEFAULT NULL

#define IndicatorLightCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    r,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    g,                 3) \
X(a, STATIC,   SINGULAR, FLOAT,    b,                 4)
#define IndicatorLightCommand_CALLBACK NULL
#define IndicatorLightCommand_DEFAULT NULL

#define PrestoState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     e_stop,            2) \
X(a, STATIC,   SINGULAR, BOOL,     autonomy_switch,   3)
#define PrestoState_CALLBACK NULL
#define PrestoState_DEFAULT NULL

#define SensorBState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    voltage_v,         2) \
X(a, STATIC,   SINGULAR, FLOAT,    current_a,         3) \
X(a, STATIC,   SINGULAR, FLOAT,    pressure_pa,       4)
#define SensorBState_CALLBACK NULL
#define SensorBState_DEFAULT NULL

#define DebugInfo_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   message,           2)
#define DebugInfo_CALLBACK pb_default_field_callback
#define DebugInfo_DEFAULT NULL

#define Envelope_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,motor_cmd,payload.motor_cmd),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,indicator_cmd,payload.indicator_cmd),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,presto_state,payload.presto_state),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,sensorb_state,payload.sensorb_state),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,debug_info,payload.debug_info),  14)
#define Envelope_CALLBACK NULL
#define Envelope_DEFAULT NULL
#define Envelope_header_MSGTYPE Header
#define Envelope_payload_motor_cmd_MSGTYPE MotorCommand
#define Envelope_payload_indicator_cmd_MSGTYPE IndicatorLightCommand
#define Envelope_payload_presto_state_MSGTYPE PrestoState
#define Envelope_payload_sensorb_state_MSGTYPE SensorBState
#define Envelope_payload_debug_info_MSGTYPE DebugInfo

extern const pb_msgdesc_t Header_msg;
extern const pb_msgdesc_t MotorCommand_msg;
extern const pb_msgdesc_t IndicatorLightCommand_msg;
extern const pb_msgdesc_t PrestoState_msg;
extern const pb_msgdesc_t SensorBState_msg;
extern const pb_msgdesc_t DebugInfo_msg;
extern const pb_msgdesc_t Envelope_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Header_fields &Header_msg
#define MotorCommand_fields &MotorCommand_msg
#define IndicatorLightCommand_fields &IndicatorLightCommand_msg
#define PrestoState_fields &PrestoState_msg
#define SensorBState_fields &SensorBState_msg
#define DebugInfo_fields &DebugInfo_msg
#define Envelope_fields &Envelope_msg

/* Maximum encoded size of messages (where known) */
/* DebugInfo_size depends on runtime parameters */
/* Envelope_size depends on runtime parameters */
#define Header_size                              2
#define IndicatorLightCommand_size               15
#define MotorCommand_size                        40
#define PrestoState_size                         4
#define ROBOSUB_PB_H_MAX_SIZE                    MotorCommand_size
#define SensorBState_size                        15

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
